src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'title')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255, unique:true)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'posts')]
    private Collection $categories_id;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    public function __construct()
    {
        $this->categories_id = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable()) ;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user;
    }

    public function setUserId(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategoriesId(): Collection
    {
        return $this->categories_id;
    }

    public function addCategoriesId(Categories $categoriesId): static
    {
        if (!$this->categories_id->contains($categoriesId)) {
            $this->categories_id->add($categoriesId);
        }

        return $this;
    }

    public function removeCategoriesId(Categories $categoriesId): static
    {
        $this->categories_id->removeElement($categoriesId);

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    protected ?string $plainPassword;


    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $rgpd = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Posts::class, orphanRemoval: true)]
    private Collection $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable());

    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getRgpd(): ?int
    {
        return $this->rgpd;
    }

    public function setRgpd(int $rgpd): static
    {
        $this->rgpd = $rgpd;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Posts>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPosts(Posts $posts): static
    {
        if (!$this->posts->contains($posts)) {
            $this->posts->add($posts);
            $posts->setUserId($this);
        }

        return $this;
    }

    public function removePosts(Posts $posts): static
    {
        if ($this->posts->removeElement($posts)) {
            // set the owning side to null (unless already changed)
            if ($posts->getUserId() === $this) {
                $posts->setUserId(null);
            }
        }

        return $this;
    }


    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): static
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

}

src/Controller/GestionsController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Entity\Posts;
use App\Entity\User;
use App\Form\RegistrationFormType;
use App\Repository\CategoriesRepository;
use App\Repository\PostsRepository;
use App\Repository\UserRepository;
use App\Services\PostFilesService;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;



class GestionsController extends AbstractController
{

    #[Route('/gestions/{nPage?}', name: 'app_gestions', requirements: ["nPage" => "\d*"])]
    public function index(PostsRepository $postsRepository, Security $security, Request $request): Response
    {
        //title
        $title = "Liste des articles de tous les Authors";

        $user = $security->getUser();
        $criteria = [];
        //if user isn't admin
        if (!in_array('ROLE_ADMIN', $user->getRoles())) {
            $criteria['user'] = $user;
            $title = "Liste de vos articles";
        }

        $limit = 8; // post par page
        $nPage = $request->get('nPage', 1);
        $nPage = max($nPage, 1);
        $offset = ($nPage - 1) * $limit;
        $posts = $postsRepository->findBy($criteria, ["id" => "DESC"], $limit, $offset);
        $totalPosts = $postsRepository->count($criteria); // obtenir le nombre total de posts spécifiques à l'utilisateur
        $totalPages = ceil($totalPosts / $limit); // calculer le nombre total de pages

        // Générer la pagination
        $pagination = range(1, $totalPages);

        return $this->render('gestions/index.html.twig', [
            'posts' => $posts,
            'title' => $title,
            'nPage' => $nPage,
            'pagination' => $pagination,
        ]);
    }


    #[Route('/gestions/users', name: 'app_gestions_user')]
    public function listUser(Security       $security,
                             Request        $request,
                             UserRepository $userRepository
    ): Response
    {

        $user = $security->getUser();

        //check autorisation
        if (!$user || !in_array('ROLE_ADMIN', $user->getRoles())) {
            $this->addFlash('denied', "Accès refusé");
            return $this->redirectToRoute('app_gestions');
        }
        $users = $userRepository->findBy([], ['created_at' => 'DESC']);


        return $this->render('gestions/users.html.twig', [
            "title" => "Liste des Auteurs",
            "users" => $users
        ]);


    }


    #[Route('/gestions/add-user', name: 'app_gestions_add_user')]
    public function addUser(
        Request                     $request,
        UserPasswordHasherInterface $userPasswordHasher,
        EntityManagerInterface      $em,
        PostFilesService            $postFileService,
        ParameterBagInterface       $params,
        Security $security

    ): Response
    {


        $userAdmin = $security->getUser();

        //check autorisation
        if (!$userAdmin || !in_array('ROLE_ADMIN', $userAdmin->getRoles())) {
            $this->addFlash('denied', "Accès refusé");
            return $this->redirectToRoute('app_gestions');
        }


        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $roles = $form['roles']->getData();
            $allowedRoles = [];
            foreach ($params->get('roles_app') as $roleArray) {
                $allowedRoles[] = reset($roleArray);
            }

            if (empty($roles) || !in_array($roles, $allowedRoles)) {
                $form['roles']->addError(new FormError('Veuillez sélectionner un rôle pour cet utilisateur'));
            }
            $role = [];
            $role[] = $roles;
            $user->setRoles($role);

            if ($form->isValid()) {
                // encode the plain password
                $plainPassword = $form->get('plainPassword')->getData();
                $user->setPassword($userPasswordHasher->hashPassword($user, $plainPassword));

                try {

                    // processing the image
                    $imageFile = $form->get('image')->getData();
                    //crop adn save image
                    $filename = $postFileService->processFile($imageFile, "AVATAR");
                    $user->setAvatar($filename);

                    $em->persist($user);
                    $em->flush();

                    //redirect user  after login
                    return $this->redirectToRoute('app_gestions_user');

                } catch (UniqueConstraintViolationException $e) {
                    $this->addFlash('error', 'Cette adresse e-mail est déjà utilisée. Veuillez en choisir une autre.');
                } catch (\Exception $e) {
                    $this->addFlash('error', 'Une erreur technique est survenue, merci de réessayer ');
                    dd($e->getMessage());
                }
            }


        }

        return $this->render('registration/index.html.twig', [
            'title' => "Ajouter Un Utilisateur",
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/gestions/edit-user/{id}', name: 'app_gestions_edit_user')]
    public function editUser(
        User                        $user,
        Request                     $request,
        UserPasswordHasherInterface $userPasswordHasher,
        EntityManagerInterface      $em,
        PostFilesService            $postFileService,
        ParameterBagInterface       $params,
        Security $security
    ): Response
    {



        $userAdmin = $security->getUser();

        //check autorisation
        if (!$userAdmin || !in_array('ROLE_ADMIN', $userAdmin->getRoles())) {
            $this->addFlash('denied', "Accès refusé");
            return $this->redirectToRoute('app_gestions');
        }




        $defaultRoles = $user->getRoles();
        $defaultRoleValue = null;
        foreach ($params->get('roles_app') as $k => $ARRoles) {
            foreach ($ARRoles as $key => $role) {
                if (in_array($role, $defaultRoles)) {
                    $defaultRoleValue = $role;
                    break;
                }
            }
        }

        $form = $this->createForm(RegistrationFormType::class, $user, [
            "edit" => true,
            "defaultRole" => $defaultRoleValue
        ]);


        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $roles = $form['roles']->getData();
            $allowedRoles = [];
            foreach ($params->get('roles_app') as $roleArray) {
                $allowedRoles[] = reset($roleArray);
            }

            if (empty($roles) || !in_array($roles, $allowedRoles)) {
                $form['roles']->addError(new FormError('Veuillez sélectionner un rôle pour cet utilisateur'));
            }
            $role = [];
            $role[] = $roles;
            $user->setRoles($role);

            if ($form->isValid()) {
                // encode the plain password
                $plainPassword = $form->get('plainPassword')->getData();

                if (!empty($plainPassword)) {
                    $user->setPassword($userPasswordHasher->hashPassword($user, $plainPassword));
                }


                try {
                    // processing the image
                    $imageFile = $form->get('image')->getData();

                    if ($imageFile) {
                        //crop adn save image
                        $filename = $postFileService->processFile($imageFile, "AVATAR");
                        $user->setAvatar($filename);
                    }
                    $em->persist($user);
                    $em->flush();

                    //redirect user  after login
                    return $this->redirectToRoute('app_gestions_user');

                } catch (UniqueConstraintViolationException $e) {
                    $this->addFlash('error', 'Cette adresse e-mail est déjà utilisée. Veuillez en choisir une autre.');
                } catch (\Exception $e) {
                    $this->addFlash('error', 'Une erreur technique est survenue, merci de réessayer ');
                    dd($e->getMessage());
                }
            }


        }

        return $this->render('registration/index.html.twig', [
            'title' => "Modifier la fiche de l'utilisateur",
            'registrationForm' => $form->createView(),
        ]);
    }


    #[Route('/gestions/delete-user/{id}', name: 'app_gestions_delete_user')]
    public function deleteUser(User                   $user,
                               Security               $security,
                               EntityManagerInterface $em,
                               PostsRepository $postsRepository ,

    ): Response
    {


        $CurrentuUser = $security->getUser();

        //check autorisation
        if (!$CurrentuUser && !in_array('ROLE_ADMIN', $CurrentuUser->getRoles())) {
            $this->addFlash('failed', "Accès refusé");
            return $this->redirectToRoute('app_gestions_user');
        }


        //if article not found
        if (!$user) {

templates/gestions/add-categories.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2 class="text-center my-5">{{ title }}</h2>

    {{ form_start(form ,  {'attr': {'class': 'container-fluid position-relative m-auto mt-3'}}) }}

    <div class="d-flex flex-column m-auto " style="max-width: 900px">
        <div class="form-input">
            <span class="mt-3 mb-2 d-block text-danger">{{ form_errors(form.name) }}</span>
            <div class="input-group  mb-3">
                <label class="fw-bold input-group-text" id="form-title" for="title">Nom de la catégories</label>
                {{ form_widget(form.name,
                    {
                        "attr": {
                        "class": "form-control", 'placeholder': 'exemple : action-drole'
                    }
                    }) }}
            </div>
            <span class="mt-3 mb-2 text-danger">{{ form_errors(form.slug) }}</span>
            <div class="input-group  mb-3">
                <label class="fw-bold input-group-text" id="form-slug" for="slug">Slug Pour l'article</label>
                {{ form_widget(form.slug,
                    {
                        "attr": {
                        "class": "form-control", 'placeholder': 'exemple : Sortie de Spiderman le breton ( min: 50 characters )'
                    }
                    }) }}
            </div>
        </div>
    </div>

    <button aria-label="envoyer le formulaire" style="width: 200px"
            class="my-2 m-auto d-block  btn btn-success text-center border border-secondary rounded-pill">
        Envoyer
    </button>

    {{ form_end(form) }}



{#    <script>#}

{#        let $btnDelete = document.querySelectorAll('.btn-delete');#}
{#        $btnDelete.forEach(($e) => {#}
{#            $e.addEventListener('click', function (event) {#}
{#                event.preventDefault();#}
{#                let attr = this.getAttribute('for');#}
{#                let checkbox = document.querySelector('#' + attr);#}
{#                let value =  checkbox.value  ;#}

{#                if (checkbox.checked !== undefined && !checkbox.checked) {#}
{#                    let confirmation = confirm(`Êtes-vous sûr de vouloir supprimer la catégorie "${value}" ?`);#}
{#                    if (confirmation) {#}
{#                        checkbox.checked = true;#}
{#                    }#}
{#                } else {#}
{#                    checkbox.checked = false;#}
{#                }#}

{#            });#}
{#        });#}

{#    </script>#}
{% endblock %}

templates/gestions/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    {% for message in app.flashes('access_denied') %}
        <div style="max-width: 350px" class="alert m-auto text-center my-5 alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    {% if post is not empty %}
        {{ 'Aucun post sélectionné' }}
    {% endif %}
{% endblock %}

templates/gestions/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section>

        <div class="container-fluid bg-dark">
            <div class="container  text-md-start ">
                <a href="/gestions/add" class="btn h6 m-3 fw-bold btn-light">Ajouter un article</a>
                {% if('ROLE_ADMIN' in app.user.roles) %}
                    <a href="/gestions/add-categories" class="btn h6 m-3 fw-bold btn-light">Ajouter une Catégorie</a>
                    <a href="/gestions/delete-categories" class="btn h6 m-3 fw-bold btn-light">Supprimer une
                        Catégorie</a>
                    <a href="/gestions/users" class="btn h6 m-3 fw-bold btn-light">Liste des Auteurs</a>
                {% endif %}
            </div>
        </div>
        <div class="container-fluid">
            <h2 class="h2 m-5 text-center text-uppercase fw-bold">{{ title }}</h2>
            {% for message in app.flashes('success') %}
                <div style="max-width:300px " class="alert  m-auto my-5 alert-success text-center">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('failed') %}
                <div style="max-width:300px " class="alert  m-auto my-5 alert-danger text-center">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="row gx-3">
                {% for  article in posts %}
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <article class="card mb-5  ">
                            <div class="d-flex p-2 justify-content-left align-items-baseline">
                                <div class="image">
                                    {% if article.userId.avatar is defined and article.userId.avatar is not empty %}
                                        <a class="page-link "
                                           href="{{ path('app_posts_user' , {id: article.userId.id}) }}">
                                            <img src="/assets/images/avatar/{{ asset(article.userId.avatar) }}"
                                                 class="rounded" width="60" alt="...">
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="d-flex text-capitalize px-3 justify-content-around align-items-baseline ">
                                    <a class="page-link" href="{{ path('app_posts_user' , {id: article.userId.id}) }}">
                                        {{ article.userId.name() }}
                                        {{ article.userId.name() }}
                                    </a>
                                    <p class="fs-7 px-4 fw-light ">
                                        Créé le :
                                        {{ article.createdAt.format('d-m-Y') }}
                                    </p>
                                </div>
                            </div>

                            <a href="{{ path('app_posts', {'slug': article.slug}) }}">
                                <img src="/assets/images/square/{{ asset(article.image) }}" class="d-block w-100"
                                     alt="...">
                            </a>
                            <div class="card-body">
                                <div class="my-1">
                                    <a href="{{ path('app_edit_post', {'slug': article.slug}) }}"
                                       class="btn fw-bold btn-primary">Modifier </a>
                                    {% if('ROLE_ADMIN' in app.user.roles or app.user.id == article.userId.id) %}
                                        <a href="{{ path('app_delete_post', {'slug': article.slug}) }}"
                                           class="btn fw-bold btn-danger btn-delete">Supprimer</a>
                                    {% endif %}
                                </div>
                                <a aria-label="voirs l'article {{ article.slug }}"
                                   class="d-block card-title fst-italic   text-capitalizetext-decoration-none"
                                   href="{{ path('app_posts', {'slug': article.slug}) }}">
                                    {{ article.title|slice(0, 25) }}...
                                </a>

                                <p class="card-text text-wrap fw-bold ">
                                    {{ article.content|slice(0, 200) |raw }}...</p>
                            </div>

                            <div class="container mb-2">
                                {% for cat in article.getCategoriesId() %}
                                    <a href="/categories/{{ cat.slug }}" class="btn m-1 btn-dark">#{{ cat.name }}</a>
                                {% endfor %}
                            </div>

                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="mt-auto">
            <ul class="pagination pagination-lg justify-content-center">
                {% if nPage > 1 %}
                    <li class="page-item"><a class="page-link" href="{{ path('app_gestions', {'nPage': nPage - 1}) }}">Précédent</a>
                    </li>
                {% endif %}
                {% for page in pagination %}
                    <li class="page-item {{ (nPage == page) ? 'active' : '' }}">
                        <a class="page-link" href="{{ path('app_gestions', {'nPage': page}) }}">{{ page }}</a>
                    </li>
                {% endfor %}
                {% if pagination|length > nPage and nPage >= 1 %}
                    <li class="page-item"><a class="page-link" href="{{ path('app_gestions', {'nPage': nPage + 1 }) }}">Suivant</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </section>

    <script type="text/javascript">
        let $btnDelete = document.querySelectorAll('.btn-delete');
        $btnDelete.forEach(($e) => {
            $e.addEventListener('click', function (event) {
                event.preventDefault();
                let confirmation = confirm('Êtes-vous sûr de vouloir supprimer cet article ?');
                if (confirmation) {
                    window.location.href = this.getAttribute('href');
                }
            });
        });

    </script>





{% endblock %}

templates/gestions/users.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section>

        <div class="container-fluid bg-dark">
            <div class="container  text-md-start ">
                <a href="/gestions/add-user" class="btn h6 m-3 fw-bold btn-light">Ajouter un Auteur</a>
            </div>
        </div>
        <div class="container">
            <h2 class="h2 m-5 text-center text-uppercase fw-bold">{{ title }}</h2>
            {% for message in app.flashes('success') %}
                <div style="max-width:300px " class="alert  m-auto my-5 alert-success text-center">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('failed') %}
                <div style="max-width:300px " class="alert  m-auto my-5 alert-danger text-center">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="row gx-3">
                {% for  user in users %}
                    <div class="d-flex p-2 justify-content-left align-items-center">
                        <div class="image">
                            {% if user.avatar is defined and user.avatar is not empty %}
                                <a class="page-link "
                                   href="{{ path('app_posts_user' , {id: user.id}) }}">
                                    <img src="/assets/images/avatar/{{ asset(user.avatar) }}"
                                         class="rounded" width="200" alt="...">
                                </a>
                            {% endif %}
                        </div>
                        <div class=" ps-2 ">
                            <div class="d-flex   align-items-baseline ">
                                <span class="pe-3 fw-bold">id: {{ user.id}}</span>
                            </div>
                            <div class="d-flex   align-items-baseline ">
                                role(s):
                                {% for  role in user.roles %}
                                    <span class="pe-3 fw-bold"> {{ role }},</span>
                                {% endfor %}
                            </div>
                            <div class="d-flex text-capitalize   align-items-baseline">
                                <a class="page-link" href="{{ path('app_posts_user' , {id: user.id}) }}">
                                    {{ 'Nom & Prénom: ' ~ user.name }}
                                    {{ user.firstName }}
                                </a>
                            </div>
                            <p class="fs-7 m-0 fw-light ">
                                Créé le : {{ user.createdAt.format('d-m-Y') }}
                            </p>
                            <p class="fs-7 m-0 p-0  fw-light ">
                                Nombre d'article:  <span class="fw-bold">{{user.posts.count}}</span>
                            </p>
                            <div>
                                <a href="{{ path('app_gestions_edit_user' , {id:user.id}) }}" title="modifier cet utilisateur" style="font-size: 25px ; color: blue"
                                   class="btn  fw-bold "><i class="bi bi-pencil-square"></i></a>
                                <a href="{{ path('app_gestions_delete_user' , {id:user.id}) }}" title="Supprimer cet utilisateur" style="font-size: 25px ; color:red"
                                   class="btn fw-bold text-danger btn-delete "><i class="bi bi-person-fill-x"></i></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>


    </section>

    <script type="text/javascript">
        let $btnDelete = document.querySelectorAll('.btn-delete');
        $btnDelete.forEach(($e) => {
            $e.addEventListener('click', function (event) {
                event.preventDefault();
                let confirmation = confirm('Êtes-vous sûr de vouloir supprimer cet article ?');
                if (confirmation) {
                    window.location.href = this.getAttribute('href');
                }
            });
        });
    </script>





{% endblock %}